# Generated by Django 4.2.7 on 2025-03-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0002_medicalcenter_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcenter',
            name='password',
        ),
    ]
