# Generated by Django 4.2.7 on 2025-03-04 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0003_remove_medicalcenter_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pdf_file', models.FileField(upload_to='uploads/')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.medicalcenter')),
            ],
        ),
    ]
