# Generated by Django 4.2.7 on 2025-03-05 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0005_school_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='password',
            field=models.CharField(default='default123', max_length=255),
        ),
    ]
