# Generated by Django 4.2.7 on 2025-03-05 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0007_alter_medicalcenter_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namedr', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camp.medicalcenter')),
            ],
        ),
    ]
