# Generated by Django 4.2.7 on 2025-03-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0010_patient_patient_id_patient_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
