# Generated by Django 4.2.7 on 2025-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0011_alter_patient_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Serious', 'Serious')], default='Normal', max_length=7),
        ),
    ]
