# Generated by Django 4.2.7 on 2025-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0012_patient_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='trtplan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='condition',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Serious', 'Serious')], default='Condition', max_length=50),
        ),
    ]
