# Generated by Django 4.2.7 on 2025-03-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camp', '0013_remove_patient_pdf_file_patient_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medicalcenter',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
